[package]
name = "gyro"
version = "0.1.4"
authors = ["Daniel Lublin <daniel@lublin.se>"]

[dependencies]
irc = "0.13.6"
chrono = "0.4.6"
reqwest = "0.9.5"
regex = "1.1.0"
hyper = "0.12.19"
htmlescape = "0.3.1"
serde_json = "1.0.39"

[patch.crates-io]
'irc' = { git = "https://github.com/quite/irc", branch = "insecure" }

[build-dependencies]
git-version = "0.2.1"
